AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  tfmLambdaPyTorchFunction2CZGAZW4ZY8D:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: ''
      MemorySize: 3008
      Timeout: 30
      Role: >-
        arn:aws:iam::598823175421:role/tfmLambda-PyTorchFunctionRole-JYWLIVIYGC8J
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /invocations
            Method: POST
      Environment:
        Variables:
          MODEL_BUCKET: tfm-bucket-fact
          MODEL_KEY: model.tar.gz
      Tags:
        'lambda:createdBy': SAM
      Layers:
        - 'arn:aws:lambda:eu-west-1:934676248949:layer:pytorchv1-py36:2'
